# Site settings
name: 程序员牧场
email: qinxiongzhou@gmail.com
author: 周钦雄
url: http://itexplore.cn
github: https://github.com/qinxiongzhou/
baseurl: ""
description: 近期探索微服务架构到数据架构的闭环
meta_description: 周钦雄;个人博客;学而不思则罔;思而不学则殆;生命不止;探索不熄
motto: 生命不止 探索不熄
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: qinxiongzhou

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

